import jsPDF from "jspdf";
import {
  CATEGORIES, CATEGORY_ORDER, CategoryLabel,
  Occupation, calculateFromTasks, TaskItem,
  getOccupationSkillProfile, SECTOR_AVERAGES, SKILL_CATEGORY_META,
  SkillCategory,
} from "./data";
import { getPeerUsage } from "./data/peer-usage";

interface ReportData {
  occupationKey: string;
  occupation: Occupation;
  activeTasks: TaskItem[];
  allTasks: TaskItem[];
  language: "en" | "de";
}

const PRIMARY = [25, 50, 82];
const SLATE = [100, 116, 139];
const DARK = [30, 41, 59];
const WHITE = [255, 255, 255];
const LIGHT_BG = [248, 250, 252];

const CAT_COLORS: Record<CategoryLabel, [number, number, number]> = {
  human_led: [34, 197, 94],
  ai_assisted: [59, 130, 246],
  sensitive: [168, 85, 247],
  high_ai_potential: [249, 115, 22],
  automatable: [239, 68, 68],
};

function truncate(text: string, maxLen: number): string {
  return text.length > maxLen ? text.substring(0, maxLen - 2) + "…" : text;
}

export function generateReport(data: ReportData) {
  const { occupationKey, occupation, activeTasks, allTasks, language } = data;
  const de = language === "de";
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const H = 297;
  const M = 18;
  const CW = W - 2 * M;
  let y = 0;

  const pcts = calculateFromTasks(activeTasks);

  function addPage() {
    doc.addPage();
    y = M;
  }

  function checkSpace(needed: number) {
    if (y + needed > H - 20) addPage();
  }

  function drawHr(yPos: number) {
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(M, yPos, W - M, yPos);
  }

  // ─── COVER PAGE ───
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, W, H, "F");

  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, W, 85, "F");

  doc.setTextColor(...WHITE);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("KI KOMPASS", M, 25);

  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  const title = de ? "Dein KI-Profil" : "Your AI Profile";
  doc.text(title, M, 48);

  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  const subtitle = de ? occupation.occupation_de : occupationKey;
  doc.text(truncate(subtitle, 50), M, 62);

  doc.setFontSize(9);
  doc.setTextColor(200, 210, 230);
  doc.text(`${activeTasks.length} ${de ? "Aufgaben analysiert" : "tasks analyzed"} · ${occupation.sector}`, M, 73);

  // Cover stats boxes
  const boxY = 100;
  const boxW = (CW - 8) / 3;
  const stats = [
    { val: `${activeTasks.length}`, label: de ? "Aufgaben" : "Tasks" },
    { val: `${Math.round((pcts.human_led || 0) + (pcts.ai_assisted || 0))}%`, label: de ? "Menschlich geführt" : "Human-led" },
    { val: `${Math.round((pcts.automatable || 0) + (pcts.high_ai_potential || 0))}%`, label: de ? "KI-exponiert" : "AI-exposed" },
  ];

  stats.forEach((s, i) => {
    const bx = M + i * (boxW + 4);
    doc.setFillColor(...WHITE);
    doc.roundedRect(bx, boxY, boxW, 30, 3, 3, "F");
    doc.setTextColor(...PRIMARY);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text(s.val, bx + boxW / 2, boxY + 15, { align: "center" });
    doc.setTextColor(...SLATE);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(s.label, bx + boxW / 2, boxY + 23, { align: "center" });
  });

  // Date
  doc.setTextColor(...SLATE);
  doc.setFontSize(8);
  const dateStr = new Date().toLocaleDateString(de ? "de-DE" : "en-US", { year: "numeric", month: "long", day: "numeric" });
  doc.text(dateStr, W / 2, 145, { align: "center" });
  doc.text(de ? "Generiert von KI Kompass · ki-kompass.replit.app" : "Generated by KI Kompass · ki-kompass.replit.app", W / 2, 152, { align: "center" });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(180, 180, 180);
  doc.text(de ? "Daten basierend auf BERUFENET · 540 Berufe · 6.079 Aufgaben" : "Data based on BERUFENET · 540 occupations · 6,079 tasks", W / 2, H - 15, { align: "center" });

  // ─── PAGE 2: AI EXPOSURE BREAKDOWN ───
  addPage();
  y = M;

  doc.setTextColor(...PRIMARY);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(de ? "KI-Expositions-Analyse" : "AI Exposure Analysis", M, y);
  y += 4;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...SLATE);
  doc.text(de ? `Basierend auf ${activeTasks.length} aktiven Aufgaben deines Profils` : `Based on ${activeTasks.length} active tasks in your profile`, M, y + 4);
  y += 12;

  drawHr(y);
  y += 8;

  // Donut replacement: horizontal stacked bar
  doc.setTextColor(...DARK);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(de ? "Gesamtverteilung" : "Overall distribution", M, y);
  y += 6;

  let barX = M;
  const barH = 10;
  CATEGORY_ORDER.forEach(cat => {
    const pct = pcts[cat] || 0;
    if (pct < 0.5) return;
    const segW = (pct / 100) * CW;
    const [r, g, b] = CAT_COLORS[cat];
    doc.setFillColor(r, g, b);
    doc.roundedRect(barX, y, Math.max(segW, 1), barH, 1, 1, "F");
    if (segW > 12) {
      doc.setTextColor(...WHITE);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text(`${Math.round(pct)}%`, barX + segW / 2, y + barH / 2 + 1, { align: "center" });
    }
    barX += segW;
  });
  y += barH + 8;

  // Category detail cards
  CATEGORY_ORDER.forEach(cat => {
    const pct = pcts[cat] || 0;
    const catConfig = CATEGORIES[cat];
    const [r, g, b] = CAT_COLORS[cat];
    const count = activeTasks.filter(t => t.label === cat).length;

    checkSpace(16);
    doc.setFillColor(r, g, b);
    doc.roundedRect(M, y, 3, 12, 1, 1, "F");

    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(de ? catConfig.label_de : catConfig.label_en, M + 6, y + 4);

    doc.setTextColor(...SLATE);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`${Math.round(pct)}% · ${count} ${de ? "Aufgaben" : "tasks"}`, M + 6, y + 10);

    // Mini bar
    const miniBarW = 40;
    const miniBarX = W - M - miniBarW;
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(miniBarX, y + 2, miniBarW, 5, 2, 2, "F");
    if (pct > 0) {
      doc.setFillColor(r, g, b);
      doc.roundedRect(miniBarX, y + 2, Math.max((pct / 100) * miniBarW, 2), 5, 2, 2, "F");
    }

    y += 16;
  });

  // Sector comparison
  const sectorAvg = SECTOR_AVERAGES[occupation.sector];
  if (sectorAvg) {
    checkSpace(40);
    y += 4;
    drawHr(y);
    y += 8;

    doc.setTextColor(...PRIMARY);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(de ? "Vergleich mit Branchendurchschnitt" : "Comparison with sector average", M, y);
    y += 8;

    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");

    const colW = CW / 5;
    CATEGORY_ORDER.forEach((cat, i) => {
      const yours = Math.round(pcts[cat] || 0);
      const avg = Math.round((sectorAvg as any)[cat] * 100);
      const diff = yours - avg;
      const [r, g, b] = CAT_COLORS[cat];
      const cx = M + i * colW + colW / 2;

      doc.setTextColor(...DARK);
      doc.setFont("helvetica", "bold");
      doc.text(`${yours}%`, cx, y, { align: "center" });

      doc.setTextColor(...SLATE);
      doc.setFont("helvetica", "normal");
      doc.text(`avg ${avg}%`, cx, y + 5, { align: "center" });

      const diffStr = diff > 0 ? `+${diff}` : `${diff}`;
      doc.setTextColor(diff > 3 ? 239 : diff < -3 ? 34 : 100, diff > 3 ? 68 : diff < -3 ? 197 : 116, diff > 3 ? 68 : diff < -3 ? 94 : 139);
      doc.setFontSize(6);
      doc.text(diffStr, cx, y + 10, { align: "center" });

      doc.setFillColor(r, g, b);
      doc.roundedRect(cx - colW / 2 + 4, y + 13, colW - 8, 2, 1, 1, "F");

      doc.setTextColor(...SLATE);
      doc.setFontSize(6);
      const shortLabel = (de ? CATEGORIES[cat].label_de : CATEGORIES[cat].label_en).split(" ").slice(0, 2).join(" ");
      doc.text(truncate(shortLabel, 14), cx, y + 20, { align: "center" });
    });
    y += 28;
  }

  // ─── PAGE 3: TASK LIST ───
  addPage();
  y = M;

  doc.setTextColor(...PRIMARY);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(de ? "Deine Aufgaben" : "Your tasks", M, y);
  y += 10;

  const grouped: Record<CategoryLabel, TaskItem[]> = {} as any;
  CATEGORY_ORDER.forEach(cat => {
    grouped[cat] = activeTasks.filter(t => t.label === cat);
  });

  CATEGORY_ORDER.forEach(cat => {
    const tasks = grouped[cat];
    if (tasks.length === 0) return;
    const catConfig = CATEGORIES[cat];
    const [r, g, b] = CAT_COLORS[cat];

    checkSpace(14);
    doc.setFillColor(r, g, b);
    doc.roundedRect(M, y, CW, 7, 2, 2, "F");
    doc.setTextColor(...WHITE);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(`${de ? catConfig.label_de : catConfig.label_en} (${tasks.length})`, M + 3, y + 5);
    y += 10;

    tasks.forEach(task => {
      checkSpace(8);
      const text = de ? task.text_de : task.text_en;
      doc.setTextColor(...DARK);
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(truncate(text, 100), CW - 6);
      doc.text(lines, M + 4, y + 3);
      y += lines.length * 4 + 2;
    });

    y += 4;
  });

  // ─── PAGE 4: SKILLS & STRATEGIC OUTLOOK ───
  addPage();
  y = M;

  doc.setTextColor(...PRIMARY);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(de ? "Kompetenzprofil" : "Skills profile", M, y);
  y += 10;

  const profile = getOccupationSkillProfile(occupationKey);
  const catCounts: Record<string, { count: number; skills: string[] }> = {};
  profile.forEach(p => {
    const sc = p.skill.category;
    if (!catCounts[sc]) catCounts[sc] = { count: 0, skills: [] };
    catCounts[sc].count += p.count;
    catCounts[sc].skills.push(de ? p.skill.name_de || p.skill.name : p.skill.name);
  });

  const sortedCats = Object.entries(catCounts).sort((a, b) => b[1].count - a[1].count);
  const totalMentions = sortedCats.reduce((sum, [, d]) => sum + d.count, 0);

  sortedCats.forEach(([cat, data]) => {
    const meta = SKILL_CATEGORY_META[cat as SkillCategory];
    if (!meta) return;
    const pct = totalMentions > 0 ? Math.round((data.count / totalMentions) * 100) : 0;

    checkSpace(18);

    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(`${de ? meta.label_de : meta.label_en}  ${pct}%`, M, y + 4);

    const barW = 60;
    const bx = W - M - barW;
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(bx, y, barW, 5, 2, 2, "F");
    doc.setFillColor(...PRIMARY);
    doc.roundedRect(bx, y, Math.max((pct / 100) * barW, 2), 5, 2, 2, "F");

    doc.setTextColor(...SLATE);
    doc.setFontSize(6.5);
    doc.setFont("helvetica", "normal");
    const skillList = data.skills.slice(0, 4).join(", ") + (data.skills.length > 4 ? ` +${data.skills.length - 4}` : "");
    doc.text(truncate(skillList, 80), M, y + 10);

    y += 16;
  });

  // ─── STRATEGIC RECOMMENDATIONS ───
  checkSpace(80);
  y += 6;
  drawHr(y);
  y += 10;

  doc.setTextColor(...PRIMARY);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(de ? "Strategische Empfehlungen" : "Strategic recommendations", M, y);
  y += 10;

  const aiExposedPct = Math.round((pcts.automatable || 0) + (pcts.high_ai_potential || 0));
  const humanCorePct = Math.round((pcts.human_led || 0) + (pcts.ai_assisted || 0));
  const autoCount = activeTasks.filter(t => t.label === "automatable").length;
  const highAiCount = activeTasks.filter(t => t.label === "high_ai_potential").length;
  const humanCount = activeTasks.filter(t => t.label === "human_led").length;

  interface Rec { icon: string; title_en: string; title_de: string; body_en: string; body_de: string }
  const recs: Rec[] = [];

  if (aiExposedPct > 30) {
    recs.push({
      icon: "!",
      title_en: "High AI exposure — act now",
      title_de: "Hohe KI-Exposition — jetzt handeln",
      body_en: `${aiExposedPct}% of your tasks are in high-exposure categories. Learn the AI tools your peers already use for these tasks. Focus on becoming the person who orchestrates AI output, not competes with it.`,
      body_de: `${aiExposedPct}% deiner Aufgaben liegen in hochexponierten Kategorien. Lerne die KI-Tools, die deine Kollegen bereits nutzen. Werde die Person, die KI-Ergebnisse orchestriert, statt mit ihnen zu konkurrieren.`,
    });
  } else if (aiExposedPct > 15) {
    recs.push({
      icon: "→",
      title_en: "Moderate AI exposure — stay ahead",
      title_de: "Moderate KI-Exposition — bleib vorne",
      body_en: `${aiExposedPct}% of your tasks have AI potential. Start experimenting with AI tools for your most repetitive tasks. Your role is shifting, not disappearing.`,
      body_de: `${aiExposedPct}% deiner Aufgaben haben KI-Potenzial. Experimentiere mit KI-Tools für deine repetitivsten Aufgaben. Deine Rolle verändert sich, verschwindet aber nicht.`,
    });
  }

  if (humanCorePct > 50) {
    recs.push({
      icon: "✓",
      title_en: "Strong human core — your advantage",
      title_de: "Starker menschlicher Kern — dein Vorteil",
      body_en: `${humanCorePct}% of your work requires human judgment, empathy, or oversight. Double down on these skills — they become more valuable as AI handles routine work around them.`,
      body_de: `${humanCorePct}% deiner Arbeit erfordert menschliches Urteilsvermögen, Empathie oder Aufsicht. Stärke diese Fähigkeiten — sie werden wertvoller, wenn KI Routinearbeit übernimmt.`,
    });
  }

  if (autoCount > 0) {
    recs.push({
      icon: "⚡",
      title_en: "Automate to free up time",
      title_de: "Automatisiere, um Zeit freizusetzen",
      body_en: `${autoCount} of your tasks are automatable. Identify 2-3 you can delegate to AI tools this month. The time saved can be redirected to higher-value work.`,
      body_de: `${autoCount} deiner Aufgaben sind automatisierbar. Identifiziere 2-3, die du diesen Monat an KI-Tools delegieren kannst. Die gewonnene Zeit investierst du in wertvollere Arbeit.`,
    });
  }

  if (highAiCount > 0) {
    recs.push({
      icon: "↑",
      title_en: "Shift to review & orchestration",
      title_de: "Wechsel zu Review & Orchestrierung",
      body_en: `${highAiCount} tasks are moving toward "AI does the first pass, you review." Learn to evaluate AI output critically — prompt engineering and quality control become core skills.`,
      body_de: `${highAiCount} Aufgaben bewegen sich Richtung „KI macht den ersten Entwurf, du prüfst." Lerne KI-Ergebnisse kritisch zu bewerten — Prompt-Engineering und Qualitätskontrolle werden Kernkompetenzen.`,
    });
  }

  recs.push({
    icon: "★",
    title_en: "Build your AI toolkit",
    title_de: "Baue dein KI-Toolkit auf",
    body_en: "Start with one general-purpose tool (ChatGPT, Claude) and one domain-specific tool for your field. Use them daily for 2 weeks before evaluating impact.",
    body_de: "Starte mit einem Allzweck-Tool (ChatGPT, Claude) und einem fachspezifischen Tool. Nutze sie 2 Wochen täglich, bevor du den Effekt bewertest.",
  });

  recs.forEach(rec => {
    checkSpace(22);

    doc.setFillColor(248, 250, 252);
    doc.roundedRect(M, y, CW, 18, 2, 2, "F");

    doc.setFillColor(...PRIMARY);
    doc.roundedRect(M, y, 3, 18, 1, 1, "F");

    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(de ? rec.title_de : rec.title_en, M + 6, y + 5);

    doc.setTextColor(...SLATE);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    const bodyLines = doc.splitTextToSize(de ? rec.body_de : rec.body_en, CW - 10);
    doc.text(bodyLines, M + 6, y + 10);

    y += 22;
  });

  // ─── PEER ADOPTION (if available) ───
  const peerData = getPeerUsage(occupation.sector);
  if (peerData) {
    checkSpace(50);
    y += 4;
    drawHr(y);
    y += 10;

    doc.setTextColor(...PRIMARY);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(de ? "KI-Nutzung in deinem Feld" : "AI adoption in your field", M, y);
    y += 4;

    doc.setTextColor(...SLATE);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`${de ? peerData.label_de : peerData.label_en} — ${peerData.adoption_pct}% ${de ? "Adoption" : "adoption"}`, M, y + 4);
    y += 12;

    peerData.stats.forEach(s => {
      checkSpace(12);
      doc.setTextColor(...DARK);
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(`• ${de ? s.stat_de : s.stat_en}`, CW - 4);
      doc.text(lines, M + 2, y + 3);
      doc.setTextColor(180, 180, 180);
      doc.setFontSize(6);
      doc.text(s.source, M + 2, y + 3 + lines.length * 3.5);
      y += lines.length * 3.5 + 5;
    });

    if (peerData.topTools.length > 0) {
      checkSpace(20);
      y += 2;
      doc.setTextColor(...DARK);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text(de ? "Populäre Tools:" : "Popular tools:", M, y + 3);
      y += 7;

      peerData.topTools.forEach((t, i) => {
        checkSpace(8);
        doc.setTextColor(...DARK);
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "bold");
        doc.text(`${i + 1}. ${t.tool}`, M + 2, y + 3);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...SLATE);
        doc.text(`— ${de ? t.tasks_de : t.tasks_en}`, M + 2 + doc.getTextWidth(`${i + 1}. ${t.tool} `), y + 3);
        y += 6;
      });
    }
  }

  // ─── FINAL FOOTER ON LAST PAGE ───
  doc.setTextColor(180, 180, 180);
  doc.setFontSize(6);
  doc.text(de
    ? "KI Kompass · Daten: BERUFENET · Quellen: DORA, Anthropic, OpenAI, Bitkom, McKinsey, Deloitte u.a."
    : "KI Kompass · Data: BERUFENET · Sources: DORA, Anthropic, OpenAI, Bitkom, McKinsey, Deloitte et al.",
    W / 2, H - 10, { align: "center" });

  doc.setTextColor(200, 200, 200);
  doc.text(de ? "Dies ist eine automatisch generierte Analyse. Keine Beratung." : "This is an auto-generated analysis. Not professional advice.", W / 2, H - 6, { align: "center" });

  // Save
  const slug = occupationKey.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "").substring(0, 30);
  doc.save(`ki-kompass-${slug}-report.pdf`);
}
